title: Everardo Padilla
description: I'm Everardo Padilla, a cybersecurity consultant that likes to create and break things. This is my personal blog where I write about stuff that interests me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark

# Profile information
name: Everardo Padilla
tagline: Cybersecurity Consultant
about-description: I'm Everardo Padilla, a cybersecurity consultant that likes to create and break things. This is my personal blog where I write about stuff that interests me.
# pic: pic.jpg

# Contact links
website: epadillas.github.io
github: epadillas
# linkedin:

# Tracker
analytics: UA-113019047-1

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets
    - _posts/assets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
